### ISSUE TITLE
VueUiQuickChart ignores dataset names

### ISSUE THREAD

**Issue by djomlastic** [graphieros/vue-data-ui#122]
You can see it on the docs page, names start with "Serie 0" instead of "Serie1". 2.3.54 seems to be the last version where this doesn't happen.

**Comment by graphieros** [comment]
Hi @djomlastic 

Thanks for spotting that!

The unit test was giving false positives for that, as it tested with dataset names corresponding to the default ('serie' + n, when no name is provided by the user, which is pretty stupid 😑).

Fixed in [v2.3.99](https://github.com/graphieros/vue-data-ui/releases/tag/v2.3.99).

**Comment by djomlastic** [comment]
You're welcome, @graphieros !

Thank you for your awesome library, and for providing a fix so quick!
