### ISSUE TITLE
Algorithm selection for which you want to increase data dilution

### ISSUE THREAD

**Issue by khcshell** [graphieros/vue-data-ui#123]
Big data (data above 10,000 levels) will cause page lag, can you dilute a data function, for example: 'lttb': using the Largest-Triangle-Three-Bucket algorithm,
      The trend, shape and extrema of the sampled lines can be guaranteed to the greatest extent.
      However, it may take a long time for the page to render
'average': Takes the average of the filter points
'min': Take the minimum value of the filter point
'max': takes the maximum value of the filter point
'minmax': takes the maximum extreme value of the absolute value of the filter point
'sum': takes the sum of the filter points

**Comment by graphieros** [comment]
Hi @khcshell 
That's a very cool suggestion, thank you.
I'm looking into it.

**Comment by graphieros** [comment]
[v2.4.11](https://github.com/graphieros/vue-data-ui/releases/tag/v2.4.11)  implements LTTB for the following charts, which are the most susceptible to be used with large datasets:

| Component       | Default Threshold | Remark                                                    |
| --------------- | ----------------- | --------------------------------------------------------- |
| VueUiXy         | 500               |                                                           |
| VueUiXyCanvas   | 10000             | Since this chart uses canvas, threhsold can be set higher |
| VueUiQuadrant   | 500               |                                                           |
| VueUiScatter    | 500               |                                                           |
| VueUiSparkline  | 500               |                                                           |
| VueUiSparkTrend | 500               |                                                           |
